# Generated by Django 4.2.3 on 2023-07-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateField()),
                ('foto', models.FileField(blank=True, upload_to='')),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=100)),
                ('puesto', models.CharField(max_length=30)),
                ('tel_casa', models.CharField(max_length=100)),
                ('tel_cel', models.CharField(max_length=10)),
                ('rfc', models.CharField(max_length=100)),
                ('seguro_social', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=100)),
                ('sueldo_hora', models.IntegerField(default=318)),
                ('sueldo_texto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
    ]
