# Generated by Django 4.2.3 on 2023-07-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='area_trabajo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='jefe_directo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='planta',
        ),
    ]
