# Generated by Django 4.2.3 on 2023-07-31 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0002_remove_empleado_area_trabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
