# Generated by Django 4.2.3 on 2023-07-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0003_alter_empleado_apellido_materno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='sueldo_hora',
            new_name='sueldo_dia',
        ),
    ]
