# Generated by Django 4.2.3 on 2023-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0006_empleado_foto_url_alter_empleado_ciudad_origen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
