# Generated by Django 4.2.3 on 2023-08-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0007_alter_empleado_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('responsabilidad', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='jefe_directo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.puesto'),
        ),
    ]
