# Generated by Django 4.2.3 on 2023-08-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0009_alter_empleado_jefe_directo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
    ]
