# Generated by Django 4.2.3 on 2023-08-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0011_empleado_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='calle',
            field=models.CharField(default='xd', max_length=100),
            preserve_default=False,
        ),
    ]
