# Generated by Django 4.2.3 on 2023-09-29 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos_humanos', '0012_empleado_calle'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recursos_humanos.planta'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='turno',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='planta',
            name='abreviatura_estado',
            field=models.CharField(default='chih', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='calle',
            field=models.CharField(default='chamizal', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='ciudad',
            field=models.CharField(default='juarez', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='colonia',
            field=models.CharField(default='Granjero', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='estado',
            field=models.CharField(default='Chihuahua', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planta',
            name='numero_de_domicilio',
            field=models.CharField(default=9999, max_length=10),
            preserve_default=False,
        ),
    ]
